name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8
          cache: maven
          server-id: github
          server-username: path-drc-bot
          server-password: MAVEN_TOKEN
      - name: Deploy to GitHub Packages
        run: mvn -B deploy --file pom.xml -DskipTests
        env:
          MAVEN_TOKEN: ${{ secrets.PATH_DRC_TOKEN }}
